name: Preflight
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
      - run: npm ci
      - name: Run preflight checks
        run: npm run preflight
      - name: Check Storybook compatibility status
        run: |
          if npm run storybook:check --silent; then
            echo "✅ Storybook compatibility confirmed - ready for reinstallation"
            echo "Run 'npm run storybook:install' to reinstall Storybook"
          else
            echo "⚠️ Storybook compatibility issues still exist"
            echo "Continue using main app at localhost:3000 for component inspection"
          fi
